export default [
  {
    "_id": "RS101",
    "name": "Rocket Propulsion",
    "number": "RS4550",
    "image": "images/RS101.jpg",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "D123",
    "credits": 4,
    "description": "This course provides an in-depth study of the fundamentals of rocket propulsion, covering topics such as propulsion theory, engine types, fuel chemistry, and the practical applications of rocket technology. Designed for students with a strong background in physics and engineering, the course includes both theoretical instruction and hands-on laboratory work"
  },
  {
    "_id": "RS102",
    "name": "Aerodynamics",
    "number": "RS4560",
    "image": "images/RS102.jpeg",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "D123",
    "credits": 3,
    "description": "This course offers a comprehensive exploration of aerodynamics, focusing on the principles and applications of airflow and its effects on flying objects. Topics include fluid dynamics, airfoil design, lift and drag forces, and the aerodynamic considerations in aircraft design. The course blends theoretical learning with practical applications, suitable for students pursuing a career in aeronautics or astronautics engineering."
  },
  {
    "_id": "RS103",
    "name": "Spacecraft Design",
    "number": "RS4570",
    "image": "images/RS103.jpg",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "D123",
    "credits": 4,
    "description": "This course delves into the principles and practices of spacecraft design, offering students a detailed understanding of the engineering and technology behind spacecraft systems. Key topics include spacecraft structure, propulsion, power systems, thermal control, and payload integration. Emphasizing both theoretical concepts and practical skills, the course prepares students for careers in the space industry, with a focus on innovative design and problem-solving in the context of current and future space missions"
  },
  {
    "_id": "RS104",
    "name": "Organic Chemistry",
    "number": "CH1230",
    "image": "images/RS104.jpg",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "D134",
    "credits": 3,
    "description": "Organic Chemistry is an in-depth course that explores the structure, properties, composition, and reactions of organic compounds and materials. The course covers various topics including hydrocarbons, functional groups, stereochemistry, and organic synthesis techniques. Students will learn about the mechanisms of organic reactions, spectroscopic methods for structure determination, and the role of organic chemistry in biological systems. Emphasis is placed on problem-solving and laboratory skills, preparing students for advanced studies in chemistry, medicine, and related fields."
  },
  {
    "_id": "RS105",
    "name": "Inorganic Chemistry",
    "number": "CH1240",
    "image": "images/RS105.jpg",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "D134",
    "credits": 3,
    "description": "Inorganic Chemistry focuses on the properties, structures, and behaviors of inorganic and organometallic compounds. This course covers a range of topics including coordination chemistry, metal complexes, bonding theories, symmetry, and crystal field theory. Students will also explore the role of inorganic chemistry in real-world applications such as catalysis, materials science, and bioinorganic processes. Laboratory work emphasizes synthesis and analysis of inorganic compounds, fostering a deeper understanding of theoretical concepts."
  },
  {
    "_id": "RS106",
    "name": "Physical Chemistry",
    "number": "CH1250",
    "image": "images/RS106.jpg",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "D134",
    "credits": 3,
    "description": "Physical Chemistry merges the principles of physics and chemistry to understand the physical properties of molecules, the forces that act upon them, and the chemical reactions they undergo. Key topics include thermodynamics, kinetics, quantum mechanics, and spectroscopy. The course provides a comprehensive understanding of molecular behavior, reaction dynamics, and the application of mathematical methods in solving chemical problems. Labs focus on experimental techniques and data analysis, equipping students with skills necessary for research and advanced study in chemistry and related fields."
  },
  {
    "_id": "RS107",
    "name": "Ancient Languages and Scripts of Middle-earth",
    "number": "ME101",
    "image": "images/RS107.jpg",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "Languages",
    "credits": 3,
    "description": "This course offers an exploration of the ancient languages and scripts found throughout Middle-earth, including Elvish (Sindarin and Quenya), Dwarvish (Khuzdul), and the Black Speech of Mordor. Students will learn the historical and cultural contexts of these languages, their linguistic structures, and their usage in various inscriptions and texts. Emphasis is on understanding the philological aspects and the role of language in shaping Middle-earth's history and lore.",
    "author": "654f9ec2ea7ead465908d1e3"
  },
  {
    "_id": "RS108",
    "name": "Wizards, Elves, and Men: Inter-species Diplomacy in Middle-earth",
    "number": "ME102",
    "image": "images/RS108.jpg",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "Political Studies",
    "credits": 4,
    "description": "This course explores the complex relationships and diplomatic interactions among the different races of Middle-earth: Elves, Men, Dwarves, and Wizards. Topics include the study of historical alliances, conflicts, and the role of leadership and wisdom in maintaining peace. Students will engage in discussions and case studies on key events in Middle-earth's history, such as the Council of Elrond and the War of the Ring, to understand the principles of diplomacy and conflict resolution in a multi-species context.",
    "author": "654f9ec2ea7ead465908d1e3"
  },
  {
    "_id": "RS109",
    "name": "History and Practice of Middle-earth Magic",
    "number": "ME103",
    "image": "images/RS109.jpg",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "Mystical Studies",
    "credits": 4,
    "description": "This course delves into the mystical and magical aspects of Middle-earth, examining the sources, practitioners, and manifestations of magic. Covering a range of magical beings, including Wizards, Elves, and Ents, as well as artifacts like the Rings of Power and Palantíri, students will learn about the philosophical and ethical dimensions of magic use. The course combines theoretical study with practical insights, offering a unique perspective on the magical forces that shape the events and destinies in the world of Middle-earth.",
    "author": "654f9ec2ea7ead465908d1e3"
  },
  {
    "_id": "RS110",
    "name": "Principles of Democratic Education",
    "number": "EDU201",
    "image": "images/RS110.jpg",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "Education",
    "credits": 3,
    "description": "This course examines the foundations of democratic education, emphasizing the role of education in fostering civic responsibility, critical thinking, and social equality. It explores historical and contemporary models of democratic schooling, the importance of participatory learning, and the development of educational systems that reflect democratic values. Students will engage in discussions on the challenges and opportunities of implementing democratic principles in diverse educational settings."
  },
  {
    "_id": "RS111",
    "name": "Philosophy of Independence and Liberation",
    "number": "HIS301",
    "image": "images/RS111.jpg",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "History",
    "credits": 4,
    "description": "This course provides an in-depth analysis of the philosophical underpinnings of independence and liberation movements, with a focus on Latin American history. It covers the ideologies that fueled the fight for independence, the impact of Enlightenment thought, and the contributions of key figures like Simón Bolívar. The course encourages students to critically examine the concepts of freedom, autonomy, and nation-building in the context of historical and contemporary struggles for liberation."
  },
  {
    "_id": "RS112",
    "name": "Innovations in Early 19th Century Education",
    "number": "EDU303",
    "image": "images/RS112.jpg",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "Education",
    "credits": 3,
    "description": "Focusing on the early 19th century, this course explores innovative educational practices and theories of the time. It highlights the work of leading educational reformers, including Simon Rodríguez, and their contributions to modern pedagogy. Students will study the evolution of educational methods, the integration of practical and theoretical knowledge, and the role of education in social change. The course includes a critical assessment of the lasting impacts of these early innovations on contemporary education systems."
  },
  {
    "_id": "RS113",
    "name": "Foundations of Christian Ethics",
    "number": "THEO101",
    "image": "images/RS113.jpeg",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "Theology",
    "credits": 3,
    "description": "This course explores the core principles of Christian ethics as derived from biblical texts and theological traditions. It covers topics such as moral decision-making, virtues and vices, and the role of faith in ethical living. Students will examine contemporary moral issues through the lens of Christian ethics, learning to apply these principles in various real-life contexts. The course encourages critical thinking and compassionate action guided by Christian values.",
    "author": "65500111ea7ead465908d1fa"
  },
  {
    "_id": "RS114",
    "name": "Early Christianity and the Apostolic Age",
    "number": "HIS201",
    "image": "images/RS114.jpg",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "History",
    "credits": 4,
    "description": "This historical course delves into the development of early Christian communities and the Apostolic Age. It focuses on the life and teachings of Jesus Christ, the role of the Apostles, and the spread of Christianity across the Roman Empire. Students will explore primary sources, including the New Testament, to understand the challenges and triumphs of the early Church. The course also examines the formation of key Christian doctrines and the historical context of the Apostolic era.",
    "author": "65500111ea7ead465908d1fa"
  },
  {
    "_id": "RS115",
    "name": "Leadership and Service in Christian Communities",
    "number": "MIN301",
    "image": "images/RS115.jpg",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "Ministry",
    "credits": 3,
    "description": "This course offers insights into effective leadership and service within Christian communities. Drawing on biblical teachings and the example of Saint Peter, it addresses the spiritual, ethical, and practical aspects of Christian leadership. Topics include pastoral care, community building, servant leadership, and the stewardship of church resources. Students will engage in practical exercises and discussions, preparing them for various roles in ministry and community service.",
    "author": "65500111ea7ead465908d1fa"
  },
  {
    "_id": "RS116",
    "name": "React JS",
    "number": "CS301",
    "image": "images/RS116.jpg",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "Computer Science",
    "credits": 4,
    "description": "This course offers a comprehensive study of React JS, a popular JavaScript library for building user interfaces. Topics covered include component-based architecture, state and props management, lifecycle methods, hooks, and modern React features like Context API and Redux. Designed for students with a strong foundation in JavaScript, this course includes both theoretical lessons and hands-on projects to build dynamic, scalable web applications.",
    "author": "655000a4ea7ead465908d1f5"
  },
  {
    "_id": "RS117",
    "name": "Database Management Systems",
    "number": "CS302",
    "image": "images/RS117.jpeg",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "Computer Science",
    "credits": 4,
    "description": "This course provides an in-depth exploration of database management systems (DBMS), focusing on fundamental concepts such as database design, normalization, indexing, and query optimization. Students will learn how to model, create, and manage relational databases using SQL. The course also covers advanced topics like transaction management, concurrency control, and database security. Ideal for students with a background in computer science, this course combines theoretical instruction with practical projects to develop real-world database solutions.",
    "author": "655000a4ea7ead465908d1f5"
  },
  {
    "_id": "RS118",
    "name": "Supervised Machine Learning",
    "number": "ML101",
    "image": "images/RS118.png",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "Machine Learning",
    "credits": 4,
    "description": "This course delves into the core principles and techniques of supervised machine learning, focusing on algorithm development for predictive modeling. Topics include regression, classification, decision trees, support vector machines, and ensemble methods such as random forests and boosting. The course also covers model evaluation, feature engineering, and hyperparameter tuning. Designed for students with a background in programming and statistics, this course integrates theoretical knowledge with hands-on projects, enabling students to build, train, and evaluate machine learning models for real-world applications.",
    "author": "655000a4ea7ead465908d1f5"
  },
  {
    "_id": "RS119",
    "name": "Unsupervised Machine Learning",
    "number": "ML102",
    "image": "images/RS119.jpg",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "Computer Science",
    "credits": 4,
    "description": "This course explores the foundational concepts and techniques of unsupervised machine learning, focusing on discovering hidden patterns and structures in data. Key topics include clustering algorithms, such as K-means and hierarchical clustering, as well as dimensionality reduction techniques like PCA and t-SNE. The course also covers anomaly detection and association rule learning. Designed for students with a background in programming and statistics, the course combines theoretical instruction with practical applications, enabling students to implement and evaluate unsupervised models on complex datasets."
  },
  {
    "_id": "RS120",
    "name": "Natural Language Processing",
    "number": "ML103",
    "image": "images/RS120.png",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "Machine Learning",
    "credits": 4,
    "description": "This course focuses on NLP techniques for text analysis, including tokenization, syntactic analysis, and modern deep learning models like BERT. Students will build applications such as chatbots and text classifiers using real-world datasets. By the end, students will be able to develop cutting-edge language processing systems for applications like sentiment analysis and machine translation."
  },
  {
    "_id": "RS121",
    "name": "Basics of Deep Learning",
    "number": "AI201",
    "image": "images/RS121.jpg",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "Artificial Intelligence",
    "credits": 4,
    "description": "This course provides a comprehensive introduction to deep learning, covering neural networks, backpropagation, and optimization techniques. Key topics include convolutional neural networks (CNNs), recurrent neural networks (RNNs), and advanced architectures like GANs and transformers. Students will gain hands-on experience building and training deep learning models using frameworks such as TensorFlow and PyTorch. By the end, they will be equipped to apply deep learning to real-world tasks such as image recognition, natural language processing, and predictive analytics."
  },
  {
    "_id": "RS122",
    "name": "Advanced Concepts of Artificial Intelligence",
    "number": "AI204",
    "image": "images/RS122.jpg",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "Artificial Intelligence",
    "credits": 4,
    "description": "This course delves into sophisticated topics in artificial intelligence, including reinforcement learning, deep reinforcement learning, generative models, and adversarial training. Students will explore AI ethics, explainable AI, and advanced optimization techniques. The curriculum combines theoretical insights with practical applications, allowing students to design and implement complex AI systems. By the end of the course, participants will be prepared to tackle cutting-edge challenges in AI and contribute to innovative solutions in various fields."
  },
  {
    "_id": "RS123",
    "name": "Artificial Intelligence and Computer Vision",
    "number": "AI206",
    "image": "images/RS123.jpg",
    "startDate": "2023-01-10",
    "endDate": "2023-05-15",
    "department": "Artificial Intelligence",
    "credits": 4,
    "description": "This course focuses on the intersection of artificial intelligence and computer vision, exploring techniques for image processing, object detection, and image segmentation. Students will learn about deep learning models, including convolutional neural networks (CNNs) and their applications in real-world scenarios such as facial recognition and autonomous driving. The course combines theoretical foundations with hands-on projects using frameworks like TensorFlow and OpenCV. By the end, students will be equipped to develop intelligent vision systems capable of interpreting and analyzing visual data."
  }
]